https://www.geeksforgeeks.org/nlp/bag-of-words-bow-model-in-nlp/

In Natural Language Processing (NLP), text data must be converted into numerical form so that machine learning algorithms can process it. The Bag of Words (BoW) model is a simple and commonly used method for this purpose.

- Converts text (sentence, paragraph, or document) into a collection of words
- Counts how often each word appears in the text
- Ignores word order and grammar, focusing only on frequency

Key Components of BoW:

- Vocabulary: It is a list of all unique words from the entire dataset. Each word in the vocabulary corresponds to a feature in the model.
- Document Representation: Each document is represented as a vector where each element shows the frequency of the words from the vocabulary in that document. The frequency of each word is used as a feature for the model.

##

In [77]:
import pandas as pd
import numpy as np
input_path = r"C:\Users\g.peyyala\OneDrive - Presight AI\Desktop\DE\Demo_setup\2026_Demo\Encoding\spam.csv"

df = pd.read_csv(input_path)
df


,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [78]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,1
5568,ham,Will ü b going to esplanade fr home?,0
5569,ham,"Pity, * was in mood for that. So...any other s...",0
5570,ham,The guy did some bitching but I acted like i'd...,0


In [79]:
df.spam.value_counts()

spam
0    4825
1     747
Name: count, dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)
X_train

883     I love to give massages. I use lots of baby oi...
3023                          How dare you change my ring
638     When ü login dat time... Dad fetching ü home now?
5248               U come n search tat vid..not finishd..
4857         yes baby! I need to stretch open your pussy!
                              ...                        
1783    My uncles in Atlanta. Wish you guys a great se...
4306                Yo come over carlos will be here soon
1480    My trip was ok but quite tiring lor. Uni start...
4529    HOW ARE U? I HAVE MISSED U! I HAVENT BEEN UP 2...
2922      Yo, any way we could pick something up tonight?
Name: Message, Length: 4457, dtype: str

In [11]:
X_train.values

<StringArray>
[                                                                                                                                              'Sorry da thangam, very very sorry i am held up with prasad.',
                                                                                                   'Eek that's a lot of time especially since American Pie is like 8 minutes long. I can't stop singing it.',
                                                                                                                                                          'That's a shame! Maybe cld meet for few hrs tomo?',
                                                              '* Was a nice day and, impressively, i was sensible, went home early and now feel fine. Or am i just boring?! When's yours, i can't remember.',
                                                                                                                                 'Will purchase d stuff today and 

In [7]:
X_train.shape

(4457,)

In [8]:
X_test.shape

(1115,)

In [9]:
y_train

2635    0
4018    0
4145    0
2667    0
694     0
       ..
4585    0
947     1
5233    0
3185    0
4810    0
Name: spam, Length: 4457, dtype: int64

In [81]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59373 stored elements and shape (4457, 7726)>

In [82]:
X_test_cv = v.transform(X_test.values)
X_test_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13668 stored elements and shape (1115, 7726)>

In [29]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7722))

In [30]:
X_train_cv.shape

(4457, 7722)

In [31]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      shape=(7722,), dtype=object)

In [34]:
v.get_feature_names_out()[1100:1110]

array(['as', 'asap', 'asda', 'ashes', 'ashley', 'ashwini', 'asia', 'ask',
       'askd', 'asked'], dtype=object)

In [35]:
v.vocabulary_

{'sorry': 6320,
 'da': 2163,
 'thangam': 6784,
 'very': 7254,
 'am': 950,
 'held': 3415,
 'up': 7163,
 'with': 7526,
 'prasad': 5353,
 'eek': 2557,
 'that': 6791,
 'lot': 4236,
 'of': 4891,
 'time': 6883,
 'especially': 2665,
 'since': 6158,
 'american': 955,
 'pie': 5205,
 'is': 3765,
 'like': 4135,
 'minutes': 4511,
 'long': 4213,
 'can': 1647,
 'stop': 6481,
 'singing': 6163,
 'it': 3777,
 'shame': 6050,
 'maybe': 4414,
 'cld': 1855,
 'meet': 4437,
 'for': 2963,
 'few': 2841,
 'hrs': 3552,
 'tomo': 6940,
 'was': 7368,
 'nice': 4771,
 'day': 2201,
 'and': 974,
 'impressively': 3654,
 'sensible': 6006,
 'went': 7437,
 'home': 3496,
 'early': 2525,
 'now': 4842,
 'feel': 2824,
 'fine': 2879,
 'or': 4971,
 'just': 3899,
 'boring': 1454,
 'when': 7459,
 'yours': 7694,
 'remember': 5673,
 'will': 7496,
 'purchase': 5487,
 'stuff': 6529,
 'today': 6923,
 'mail': 4337,
 'to': 6916,
 'you': 7686,
 'do': 2391,
 'have': 3379,
 'po': 5257,
 'box': 1469,
 'number': 4856,
 'ok': 4917,
 'then': 68

In [19]:
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7722))

In [20]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7722,))

In [22]:
np.where(X_train_np[10]!=0)

(array([ 948,  974, 1592, 3135, 3379, 3658, 3777, 3899, 4178, 4412, 4420,
        4463, 4468, 4551, 4561, 4842, 4934, 5700, 5999, 6038, 6795, 6916,
        7496, 7646, 7686]),)

In [36]:
X_train[:4]

2635    Sorry da thangam, very very sorry i am held up...
4018    Eek that's a lot of time especially since Amer...
4145     That's a shame! Maybe cld meet for few hrs tomo?
2667    * Was a nice day and, impressively, i was sens...
Name: Message, dtype: str

In [83]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)
model

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [84]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       0.98      0.90      0.94       150

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [85]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

- ChatGPT Version

In [42]:
import pandas as pd
import numpy as np
input_path = r"C:\Users\g.peyyala\OneDrive - Presight AI\Desktop\DE\Demo_setup\2026_Demo\Encoding\spam.csv"

df = pd.read_csv(input_path)
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,1
5568,ham,Will ü b going to esplanade fr home?,0
5569,ham,"Pity, * was in mood for that. So...any other s...",0
5570,ham,The guy did some bitching but I acted like i'd...,0


In [57]:
X = df["Message"]   # text column
y = df["spam"]      # target column

In [58]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [61]:
vectorizer = CountVectorizer(stop_words='english')

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

In [67]:
X_train_vec.toarray()[0:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7440))

In [66]:
X_test_vec.toarray()[0:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7440))

In [62]:
print(len(vectorizer.vocabulary_))

7440


In [68]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_vec, y_train)
model

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [69]:
y_pred = model.predict(X_test_vec)

print(y_pred[:10])
print(list(y_test[:10]))

[0 0 0 0 0 0 0 0 0 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [71]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9838565022421525


In [72]:
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


Classification Report:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       1.00      0.88      0.94       149

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [73]:
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)


Confusion Matrix:
 [[966   0]
 [ 18 131]]


In [74]:
cm_df = pd.DataFrame(
    cm,
    index=["Actual Ham (0)", "Actual Spam (1)"],
    columns=["Predicted Ham (0)", "Predicted Spam (1)"]
)

cm_df

,Predicted Ham (0),Predicted Spam (1)
Actual Ham (0),966,0
Actual Spam (1),18,131


- Grok Version (Both OHE & BoW)

In [86]:
# ========================================================
# FILE 2: churn_onehot_bow.py
# Method: One-Hot Encoding + BOW (Bag of Words)
# Uses CountVectorizer on CustomerFeedback text
# Beginner-friendly - Minimal steps with detailed comments
# ========================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ====================== STEP 1: Generate 150 Records ======================
print("=== STEP 1: Generating 150 synthetic customer records ===")
np.random.seed(42)

n_samples = 150

data = {
    'Gender': np.random.choice(['Male', 'Female'], n_samples),
    'Contract': np.random.choice(['Month-to-month', 'One year', 'Two year'], n_samples, p=[0.55, 0.30, 0.15]),
    'PaymentMethod': np.random.choice(['Electronic check', 'Mailed check', 'Bank transfer', 'Credit card'], n_samples),
    'InternetService': np.random.choice(['DSL', 'Fiber optic', 'No'], n_samples, p=[0.35, 0.50, 0.15]),
    'Tenure': np.random.randint(1, 73, n_samples),
    'MonthlyCharges': np.round(np.random.uniform(20, 120, n_samples), 2),
    'CustomerFeedback': np.random.choice([
        "Great service and fast speeds",
        "Poor network connection keeps dropping",
        "Excellent customer support",
        "Billing errors every month",
        "Love the pricing and value",
        "Slow internet during evenings",
        "Happy with the overall experience",
        "Contract renewal is too expensive"
    ], n_samples)
}

df = pd.DataFrame(data)

# Create target (Churn)
high_churn = (df['Tenure'] < 12) | (df['MonthlyCharges'] > 80)
df['Churn'] = np.where(high_churn,
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.75, 0.25]),
                       np.random.choice(['Yes', 'No'], n_samples, p=[0.20, 0.80]))

print(f"Total records: {df.shape[0]}")
print("Sample data:\n", df.head(5))
print("\nChurn distribution:\n", df['Churn'].value_counts())

# ====================== STEP 2: Prepare Features (X) and Target (y) ======================
X = df.drop('Churn', axis=1)   # All columns including text
y = df['Churn']

categorical_features = ['Gender', 'Contract', 'PaymentMethod', 'InternetService']
numerical_features   = ['Tenure', 'MonthlyCharges']
text_feature         = 'CustomerFeedback'

# ====================== STEP 3: Create Preprocessor with OneHot + BOW ======================
print("\n=== STEP 3: Creating preprocessor with One-Hot Encoding + BOW ===")

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features),
        ('text', CountVectorizer(max_features=50, stop_words='english'), text_feature)   # BOW here
    ],
    remainder='drop'
)

# ====================== STEP 4: Create Full Pipeline ======================
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# ====================== STEP 5: Train-Test Split ======================
print("\n=== STEP 5: Splitting data into train and test ===")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)
print(f"Training records: {X_train.shape[0]} | Test records: {X_test.shape[0]}")

# ====================== STEP 6: Train the Model ======================
print("\n=== STEP 6: Training the model ===")
pipeline.fit(X_train, y_train)

# ====================== STEP 7: Evaluate on Test Data ======================
print("\n=== STEP 7: Checking accuracy on test data ===")
y_pred = pipeline.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Accuracy: {accuracy:.2%}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ====================== STEP 8: Predict on New Data ======================
print("\n=== STEP 8: Predicting on new customer data ===")
new_data = pd.DataFrame({
    'Gender': ['Female', 'Male'],
    'Contract': ['Two year', 'Month-to-month'],
    'PaymentMethod': ['Credit card', 'Electronic check'],
    'InternetService': ['DSL', 'Fiber optic'],
    'Tenure': [48, 5],
    'MonthlyCharges': [55.75, 95.50],
    'CustomerFeedback': ["Great service and fast speeds", "Network keeps dropping"]
})

predictions = pipeline.predict(new_data)
probabilities = pipeline.predict_proba(new_data)

print("New Data:")
print(new_data)
print("\nPredictions:")
for i, (pred, prob) in enumerate(zip(predictions, probabilities)):
    print(f"Customer {i+1}: Churn = {pred} | Probability = {prob[1]:.2%}")

print("\n🎉 One-Hot + BOW script complete!")

=== STEP 1: Generating 150 synthetic customer records ===
Total records: 150
Sample data:
    Gender        Contract     PaymentMethod InternetService  Tenure  \
0    Male        One year      Mailed check             DSL      61   
1  Female        One year      Mailed check     Fiber optic      54   
2    Male  Month-to-month      Mailed check     Fiber optic      39   
3    Male  Month-to-month      Mailed check     Fiber optic      19   
4    Male  Month-to-month  Electronic check     Fiber optic      39   

   MonthlyCharges                   CustomerFeedback Churn  
0           32.80  Happy with the overall experience    No  
1           35.19  Contract renewal is too expensive    No  
2           33.88      Slow internet during evenings    No  
3           84.09  Contract renewal is too expensive   Yes  
4           38.19         Excellent customer support    No  

Churn distribution:
 Churn
No     77
Yes    73
Name: count, dtype: int64

=== STEP 3: Creating preprocessor with On

## Bigrams and N-Grams¶
In the example illustrated in the figure at the beginning of this notebook, we used the so-called 1-gram (unigram) tokenization: Each token represents a single element with regard to the splittling criterion.

Entirely discarding word order is not always a good idea, as composite phrases often have specific meaning, and modifiers like “not” can invert the meaning of words.

A simple way to include some word order are n-grams, which don’t only look at a single token, but at all pairs of neighborhing tokens. For example, in 2-gram (bigram) tokenization, we would group words together with an overlap of one word; in 3-gram (trigram) splits we would create an overlap two words, and so forth:

original text: “this is how you get ants”

1-gram: “this”, “is”, “how”, “you”, “get”, “ants”

2-gram: “this is”, “is how”, “how you”, “you get”, “get ants”

3-gram: “this is how”, “is how you”, “how you get”, “you get ants”

Which “n” we choose for “n-gram” tokenization to obtain the optimal performance in our predictive model depends on the learning algorithm, dataset, and task. Or in other words, we have consider “n” in “n-grams” as a tuning parameters, and in later notebooks, we will see how we deal with these.

In [87]:
# look at sequences of tokens of minimum length 2 and maximum length 2
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
bigram_vectorizer.fit(X)

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [ ]:
bigram_vectorizer.get_feature_names()
bigram_vectorizer.transform(X).toarray()


- Often we want to include unigrams (single tokens) AND bigrams, wich we can do by passing the following tuple as an argument to the ngram_range parameter of the CountVectorizer function:

In [ ]:
gram_vectorizer = CountVectorizer(ngram_range=(1, 2))
gram_vectorizer.fit(X)

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer(ngram_range=(1, 2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [92]:
v = CountVectorizer(ngram_range=(2, 2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor hathodawala': 4,
 'hathodawala is': 1,
 'is looking': 2,
 'looking for': 3,
 'for job': 0}